[project]
name = "dane-gov-pl-mcp"
version = "0.1.0"
description = "MCP server for dane.gov.pl API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "async-lru>=2.0.5",
    "fastexcel>=0.11.0",
    "fastmcp>=2.10.2",
    "polars>=1.31.0",
    "unstructured[all-docs]>=0.18.9",
]
