[project]
name = "dane-gov-pl-mcp"
version = "0.1.0"
description = "MCP server for dane.gov.pl API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "async-lru>=2.0.5",
    "fastmcp>=2.10.2",
    "requests>=2.32.4",
]
